export interface PropertyType {
  _id: string,
  propertyName: string,
  location: string,
  slug,
  gender: string,
  distance: string,
  rooms: number,
  sharingOptions: string,
  bathrooms: number,
  food: string,
  ro: string,
  canWater: string,
  powerBackup: string,
  wifi: string,
  refrigerator: string,
  washingMachine: string,
  airConditioner: string,
  extraEB: number,
  inTime: string,
  bookingCharges: number,
  propertyInChargeName: string,
  phoneNumber: array,
  landline: array,  
  rent: number,
  images: array,
  latitude: number,
  longitude: number, 
} 

